Move the v8 snapshot creation to build time
DataDog/datadog-static-analyzer pull request #145
Opened 2023-12-07 23:02 UTC by abhirag

## What problem are you trying to solve?
As of now we create the v8 snapshot lazily during runtime, moving the snapshot creation to build time should improve startup time
## What is your solution?
Move the snapshot creation to build time, the v8 snapshot bytes are then included in the binary
## Alternatives considered
Alternative is the current approach where we create the v8 runtime snapshot lazily during runtime
## What the reviewer should know
The tradeoff is between better startup times and a tad fatter binary. I can try and profile to get some concrete numbers if the tradeoff seems unacceptable. The approach I put forward is how Deno's cli seems to be handling snapshotting too. Also I had to fix some clippy lints ([manual_retain](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_retain), [iter_overeager_cloned](https://rust-lang.github.io/rust-clippy/master/index.html#/iter_overeager_cloned))

2023-12-14 13:51 UTC, juli1 commented
Sorry for the late reply, just looked at the project and noticed the PR! We will get back to you shortly on this!

2023-12-15 14:44 UTC, juli1 requested changes

2023-12-15 14:44 UTC, juli1 commented on kernel/build.rs
> +
Please put a comment explaining what it does. Especially that it build the snapshot that will be later used by a static variable. We may also put a reference to the cargo book about the environment variable, explaining where to put [references to `OUT_DIR`](https://doc.rust-lang.org/cargo/reference/environment-variables.html)

2023-12-15 14:44 UTC, juli1 commented on kernel/src/analysis/javascript.rs
> +static STARTUP_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/DENO_SNAPSHOT.bin"));
Put a comment that explains this file is built at compile-time in `build.rs`

2023-12-15 18:49 UTC, juli1 approved these changes

2023-12-15 18:50 UTC, abhirag commented
@juli1 Thanks for your feedback, added the required comments

2023-12-15 19:15 UTC, merged