feat: avoid processing minified JavaScript files
DataDog/datadog-static-analyzer pull request #503
Opened 2024-08-29 18:42 UTC by amaanq

## What problem are you trying to solve?

Currently, we process minified JavaScript files during analysis. These files are very expensive to parse and query, and can raise false positives. Ideally, we should not be processing them to begin with, as these are not hand-written files by programmers.

## What is your solution?

When we iterate over each language to process and fetch the files to be analyzed for the language, an additional step is added where we filter out minified files. The filtering process is done in the function `filter_out_minified_files`, and the heuristic for determining whether or not a file is minified is by checking if the average line length of the file is over 110. This is currently what GitHub does with `linguist` [here](https://github.com/github-linguist/linguist/blob/ebbedf06dc18e929104a4a3573ac43b43298a761/lib/linguist/generated.rb#L168). A test has been added where we write to a JavaScript file a few hundred characters on one line, and after filtering out minified files, we can see that the file was filtered out.

## Alternatives considered

## What the reviewer should know

2024-08-29 18:48 UTC, juli1 requested changes

2024-08-29 18:48 UTC, juli1 commented on crates/bins/src/bin/datadog-static-analyzer.rs
> +        }
1. Implement this rather as the `is_generated_file`. Look at [this](https://github.com/DataDog/datadog-static-analyzer/blob/main/crates/static-analysis-kernel/src/analysis/analyze.rs#L186) and we should implement something similar.
2. This should be enabled only when `analysis_option.ignore_generated_files` is true (similar to (1))

2024-08-29 19:02 UTC, amaanq commented
The CI failures are expected - we're no longer processing minified JS files in repos that we use to test for regressions in.

2024-08-29 20:18 UTC, amaanq commented on crates/static-analysis-kernel/src/analysis/generated_content.rs
> +        if lines.count() == 0 {
Your example with `checked_div` is much more clear & easier to read, so I'll use that, thanks!

2024-08-30 00:52 UTC, juli1 approved these changes

2024-08-30 00:52 UTC, juli1 commented
Please fix the CI pipeline + ship

2024-08-30 02:02 UTC, merged